version: '3.8'

services:
  app:
    build:
      context: ./aiservice
      dockerfile: Dockerfile
    volumes:
      - ./aiservice:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_client:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: DB_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  aspnetapp:
    build:
      context: ./aspnetapp
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql