version: '3.8'

services:
  app:
    build:
      context: ./aiservice
      dockerfile: Dockerfile
    volumes:
      - ./aiservice:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_client:/usr/share/nginx/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - mysql

  rzhdapi:
    image: rzhdapi:latest
    build:
      context: .
      dockerfile: RzhdAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  mysql_data: